name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: Restore main dependencies
      run: dotnet restore FlexibleTypes/FlexibleTypes.csproj
    - name: Restore tests dependencies
      run: dotnet restore FlexibleTypes.Tests/FlexibleTypes.Tests.csproj
    - name: Build
      run: dotnet build FlexibleTypes/FlexibleTypes.csproj --no-restore 
    - name: Build Tests
      run: dotnet build FlexibleTypes.Tests/FlexibleTypes.Tests.csproj
    - name: Run Tests
      run: /home/runner/work/FlexibleTypes/FlexibleTypes/FlexibleTypes.Tests/bin/Debug/net6.0/FlexibleTypes.Tests.exe
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FlexibleTypes.dll
        path: /home/runner/work/FlexibleTypes/FlexibleTypes/FlexibleTypes/bin/Debug/netstandard2.1/FlexibleTypes.dll
